SHELL = /bin/sh
LEX = flex -i
YACC = yacc -d
CC = gcc 
CPPFLAGS = 
CFLAGS = $(CPPFLAG) -g -O2 -DHW_LITTLE_ENDIAN
LDFLAGS = 
LIBS = -L ../libmdb -lmdb -ll `glib-config --libs` -lreadline -lncurses

INC = -I ../include `glib-config --cflags` -I/usr/include/readline
OBJS = y.tab.o lex.yy.o mdbsql.o main.o

all: mdb-sql

libmdb: $(OBJS)
	rm -f libmdb.a
	ar cq libmdb.a $(OBJS)
clean: 
	rm -f core *.o *.a y.tab.* lex.yy.c mdb-sql

lex.yy.c: sql.l
	$(LEX) $<
y.tab.c: sql.y
	$(YACC) $< 
.c.o:
	$(CC) $(CFLAGS) -g -c $< $(INC)

sql: $(OBJS)
	$(CC) -o $@ $(LDFLAGS) $(OBJS) $(LIBS)

